--2
SELECT COUNT(*) FROM TRACK
WHERE ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'АВТОБУС') 
AND id_stop = 3950
AND extract(hour from STOP_TIME_REAL) >= 6 AND extract(hour from STOP_TIME_REAL) < 7
AND TO_char(STOP_TIME_REAL, 'YYYY-MM-DD') = '2019-09-09';


--3
SELECT COUNT(DISTINCT CARRIER_BOARD_NUM) FROM TRACK
WHERE ROUTE_NUMBER = 191
AND ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'АВТОБУС')
AND extract(hour from STOP_TIME_REAL) >= 14 AND extract(hour from STOP_TIME_REAL) < 15
AND TO_char(STOP_TIME_REAL, 'YYYY-MM-DD') = '2019-09-09';
