-- 1
SELECT COUNT(*) FROM STOPS
WHERE LATITUDE BETWEEN 59.955 AND 60.01
AND LONGITUDE BETWEEN 30.252 AND 30.304;

--2
SELECT DISTINCT ROUTE_NUMBER FROM TRACK
WHERE CARRIER_BOARD_NUM = 7529;

--3
SELECT COUNT (DISTINCT CARRIER_BOARD_NUM) FROM TRACK
WHERE ROUTE_NUMBER = 30 AND ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME='АВТОБУС');

--4
SELECT MAX(DISTANCE_BACK) FROM ROUTE_BY_STOPS
WHERE ROUTE_NUMBER = 11 AND ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'ТРОЛЛЕЙБУС');


--5
SELECT SUM(DISTANCE_BACK) FROM ROUTE_BY_STOPS
WHERE ROUTE_NUMBER = 10 
AND ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'ТРОЛЛЕЙБУС')
AND ID_DIRECTION = (SELECT ID_DIRECTION FROM DIRECTION WHERE DIRECTION_TYPE = 'ПРЯМОЕ')
AND STOP_NUMBER BETWEEN 9 AND 21;
--ORDER BY STOP_NUMBER;
--SELECT * FROM DIRECTION;

--6
SELECT LATITUDE, LONGITUDE FROM STOPS
WHERE ID_STOP = (
SELECT ID_STOP FROM ROUTE_BY_STOPS
WHERE ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'АВТОБУС')
AND ROUTE_NUMBER = 46
AND ID_DIRECTION = (SELECT ID_DIRECTION FROM DIRECTION WHERE DIRECTION_TYPE = 'ОБРАТНОЕ')
AND STOP_NUMBER = 14);

--7
SELECT ROUTE_NUMBER, SUM(DISTANCE_BACK) FROM ROUTE_BY_STOPS
WHERE ID_VEHICLE = (SELECT ID_VEHICLE FROM VEHICLE WHERE VEHICLE_NAME = 'АВТОБУС')
AND ID_DIRECTION = (SELECT ID_DIRECTION FROM DIRECTION WHERE DIRECTION_TYPE = 'ОБРАТНОЕ')
GROUP BY ROUTE_NUMBER
HAVING SUM(DISTANCE_BACK) BETWEEN 10500 AND 18850;
